# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
                ('quantity', models.CharField(max_length=45)),
                ('amount', models.CharField(max_length=45)),
                ('subcidy', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
