# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('compensation_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('amount', models.IntegerField()),
                ('rules', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'compensation',
                'managed': False,
            },
        ),
    ]
