# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('account_no', models.IntegerField(db_column='account no')),
                ('amount', models.IntegerField()),
                ('bank_name', models.CharField(db_column='bank name', max_length=45)),
                ('branch_name', models.CharField(db_column='branch name', max_length=45)),
                ('ifsc_code', models.CharField(db_column='ifsc code', max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
