# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalAssistance',
            fields=[
                ('educational_assistance_id', models.AutoField(primary_key=True, serialize=False)),
                ('scolarship_name', models.CharField(db_column='scolarship name', max_length=45)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'educational_assistance',
                'managed': False,
            },
        ),
    ]
