# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReqPrawnFiltration',
            fields=[
                ('req_prawn_filtration_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_no', models.IntegerField(db_column='license no')),
                ('description', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'req_prawn_filtration',
                'managed': False,
            },
        ),
    ]
