# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefSchem',
            fields=[
                ('relief_schem_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(db_column='scheme name', max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'relief_schem',
                'managed': False,
            },
        ),
    ]
