# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(db_column='student name', max_length=45)),
                ('student_class', models.IntegerField(db_column='student class')),
                ('date_of_birth', models.DateField(db_column='date of birth')),
                ('village', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('pin_code', models.IntegerField(db_column='pin code')),
                ('district', models.CharField(max_length=45)),
                ('institution', models.CharField(max_length=45)),
                ('mark', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
