# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FisheriesOfficer',
            fields=[
                ('fisheries_officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField(db_column='date of birth')),
                ('gender', models.CharField(max_length=45)),
                ('qualification', models.CharField(max_length=45)),
                ('pincode', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('contact_no', models.CharField(db_column='contact no', max_length=30)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'fisheries_officer',
                'managed': False,
            },
        ),
    ]
