# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_name', models.CharField(db_column='insurance name', max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'insurance',
                'managed': False,
            },
        ),
    ]
