# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrawnFiltration',
            fields=[
                ('prawn_filtration_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_date', models.CharField(db_column='available date', max_length=45)),
                ('details', models.CharField(db_column='Details', max_length=500)),
            ],
            options={
                'db_table': 'prawn_filtration',
                'managed': False,
            },
        ),
    ]
