"""
Django settings for flyfishers project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%dmd=zp2g39x-@@welgq43g_j6k39m2t2o#tk9gb-029cei3i#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'alert.apps.AlertConfig',
    'compensation.apps.CompensationConfig',
    'deputydirector.apps.DeputydirectorConfig',
    'education_assistance.apps.EducationAssistanceConfig',
    'equipment.apps.EquipmentConfig',
    'fisheries_officer.apps.FisheriesOfficerConfig',
    'fishermen.apps.FishermenConfig',
    'freenet_license.apps.FreenetLicenseConfig',
    'insurance.apps.InsuranceConfig',
    'login.apps.LoginConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'vessel_license.apps.VesselLicenseConfig',
    'prawn_filtration.apps.PrawnFiltrationConfig',
    'relief_scheme.apps.ReliefSchemeConfig',
    'request_compensation.apps.RequestCompensationConfig',
    # 'request_education.apps.RequestEducationConfig',
    'request_vessel_license.apps.RequestVesselLicenseConfig',
    'request_freenet_license.apps.RequestFreenetLicenseConfig',
    'request_insurance.apps.RequestInsuranceConfig',
    'request_prawn_filtration.apps.RequestPrawnFiltrationConfig',
    'request_releif_scheme.apps.RequestReleifSchemeConfig',
    'student.apps.StudentConfig',
    'trolling.apps.TrollingConfig',
    'vessel.apps.VesselConfig',
    'temp.apps.TempConfig',
    'message.apps.MessageConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flyfishers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flyfishers.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ccsitv_flyfishers',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT':'3309',

    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

import  os
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'static')

STATIC_URL = '/static/'

STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'STATIC'),
]
import mimetypes
mimetypes.add_type("text/css",".css",True)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
