# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReqCompensation',
            fields=[
                ('req_compensation_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user name', max_length=45)),
                ('reason', models.CharField(max_length=45)),
                ('proof', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'req_compensation',
                'managed': False,
            },
        ),
    ]
