# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VesselLicense',
            fields=[
                ('vessel_license_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_vessel', models.CharField(db_column='type of vessel', max_length=45)),
                ('license_type', models.CharField(db_column='license type', max_length=45)),
            ],
            options={
                'db_table': 'vessel_license',
                'managed': False,
            },
        ),
    ]
