# Generated by Django 3.2.19 on 2023-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReqFreenetLicense',
            fields=[
                ('req_freenet_license_id', models.AutoField(primary_key=True, serialize=False)),
                ('fishermen_id', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'req_freenet_license',
                'managed': False,
            },
        ),
    ]
